import { describe, it, expect } from 'vitest'
import { parseReceiverLayout } from './receiverLayout'

/**
 * The shape make_multirx_cfg.py actually writes, trimmed to the fields
 * parseReceiverLayout() reads.
 *
 * Deliberately a fixture rather than a read of the repo's own
 * `lwin_both.json`: that file is regenerated by every capture start, so a
 * test that read it would pass or fail depending on which session happened to
 * be running — and would stop covering the two-leg case entirely the first
 * time somebody ran a single-leg capture.
 */
function config(
  devices: unknown[],
  channels: unknown[],
): string {
  return JSON.stringify({ devices, channels })
}

const DEV_700 = { name: 'one', frequency: 771418500, rate: 8000000 }
const DEV_800 = { name: 'pro', frequency: 855725000, rate: 12000000 }

function voice(name: string, device: string) {
  // The real entries carry whitelist/blacklist/crypt_keys paths too; they are
  // omitted here precisely because nothing in the derivation may read them.
  return { name, device, frequency: 769681250 }
}

/** The live layout as of session 33: 1 CC + 3 voice on 700, 7 voice on 800. */
function session33(): string {
  return config([DEV_700, DEV_800], [
    { name: 'CC', device: 'one', frequency: 773056250 },
    voice('VC700_0', 'one'), voice('VC700_1', 'one'), voice('VC700_2', 'one'),
    voice('VC800_0', 'pro'), voice('VC800_1', 'pro'), voice('VC800_2', 'pro'),
    voice('VC800_3', 'pro'), voice('VC800_4', 'pro'), voice('VC800_5', 'pro'),
    voice('VC800_6', 'pro'),
  ])
}

describe('parseReceiverLayout', () => {
  it('reads two radios and the per-leg voice split from a real two-leg config', () => {
    const layout = parseReceiverLayout(session33())
    expect(layout).not.toBeNull()
    expect(layout?.radios).toBe(2)
    expect(layout?.legs.map(l => ({ band: l.bandMhz, voice: l.voice, control: l.control }))).toEqual([
      { band: 700, voice: 3, control: 1 },
      { band: 800, voice: 7, control: 0 },
    ])
  })

  it('does not count the control channel as a voice receiver', () => {
    // 11 channels in the config; 10 of them record audio. Getting this wrong
    // overstates the concurrent-call pool by exactly one — the number an
    // operator reads this display to reason about.
    const layout = parseReceiverLayout(session33())
    expect(layout?.voiceTotal).toBe(10)
    expect(layout?.controlTotal).toBe(1)
  })

  it('attributes the control channel to the leg it is bound to, not the first leg', () => {
    const layout = parseReceiverLayout(config([DEV_700, DEV_800], [
      { name: 'CC', device: 'pro', frequency: 855000000 },
      voice('VC700_0', 'one'),
    ]))
    expect(layout?.legs.find(l => l.device === 'one')?.control).toBe(0)
    expect(layout?.legs.find(l => l.device === 'pro')?.control).toBe(1)
  })

  it('counts a second control receiver (CC_1) as control, not voice', () => {
    const layout = parseReceiverLayout(config([DEV_700, DEV_800], [
      { name: 'CC', device: 'one', frequency: 773056250 },
      { name: 'CC_1', device: 'pro', frequency: 855000000 },
      voice('VC700_0', 'one'),
    ]))
    expect(layout?.controlTotal).toBe(2)
    expect(layout?.voiceTotal).toBe(1)
  })

  it('derives the band by flooring the tuned centre, so 771.4 MHz is the 700 MHz leg', () => {
    // Rounding instead of flooring sends 771.4185 MHz to 800 and labels both
    // legs "800 MHz" — the specific wrong answer this guards.
    const layout = parseReceiverLayout(config([DEV_700], []))
    expect(layout?.legs[0]?.bandMhz).toBe(700)
    expect(layout?.legs[0]?.centreHz).toBe(771418500)
  })

  it('reports a single-leg capture as one radio', () => {
    const layout = parseReceiverLayout(config([DEV_800], [
      { name: 'CC', device: 'pro', frequency: 855000000 },
      voice('VC800_0', 'pro'), voice('VC800_1', 'pro'),
    ]))
    expect(layout?.radios).toBe(1)
    expect(layout?.voiceTotal).toBe(2)
    expect(layout?.legs).toHaveLength(1)
  })

  it('ignores a channel bound to a device the config never declares', () => {
    // multi_rx.py has no radio to give it, so it cannot receive anything.
    const layout = parseReceiverLayout(config([DEV_700], [
      voice('VC700_0', 'one'),
      voice('VC800_0', 'pro'),   // 'pro' is not in devices here
    ]))
    expect(layout?.radios).toBe(1)
    expect(layout?.voiceTotal).toBe(1)
  })

  it('drops a device entry with no name or no centre frequency, keeping the rest', () => {
    const layout = parseReceiverLayout(config(
      [DEV_700, { name: 'pro' }, { frequency: 855725000 }],
      [voice('VC700_0', 'one')],
    ))
    expect(layout?.radios).toBe(1)
    expect(layout?.legs[0]?.device).toBe('one')
  })

  it('returns a zeroed layout, not null, for a config with devices and no channels', () => {
    // A real config that would open two radios and receive nothing. Saying so
    // is more useful than degrading to silence.
    const layout = parseReceiverLayout(config([DEV_700, DEV_800], []))
    expect(layout).toEqual({
      radios: 2,
      voiceTotal: 0,
      controlTotal: 0,
      legs: [
        { device: 'one', centreHz: 771418500, bandMhz: 700, voice: 0, control: 0 },
        { device: 'pro', centreHz: 855725000, bandMhz: 800, voice: 0, control: 0 },
      ],
    })
  })

  describe('degrades quietly rather than reporting a layout it cannot read', () => {
    it('on an empty file — a fresh checkout where no capture has ever run', () => {
      expect(parseReceiverLayout('')).toBeNull()
    })

    it('on a half-written file (the generator rewrites it on every start)', () => {
      expect(parseReceiverLayout('{"devices": [{"name": "one",')).toBeNull()
    })

    it('on valid JSON that is not a config object', () => {
      expect(parseReceiverLayout('[]')).toBeNull()
      expect(parseReceiverLayout('null')).toBeNull()
      expect(parseReceiverLayout('"lwin_both.json"')).toBeNull()
      expect(parseReceiverLayout('{}')).toBeNull()
    })

    it('when channels is missing or not an array', () => {
      expect(parseReceiverLayout(JSON.stringify({ devices: [DEV_700] }))).toBeNull()
      expect(parseReceiverLayout(JSON.stringify({ devices: [DEV_700], channels: {} }))).toBeNull()
    })

    it('when devices is missing, empty, or has no usable entry', () => {
      expect(parseReceiverLayout(JSON.stringify({ channels: [] }))).toBeNull()
      expect(parseReceiverLayout(config([], [voice('VC700_0', 'one')]))).toBeNull()
      expect(parseReceiverLayout(config([{ name: '' }, 7], [voice('VC700_0', 'one')]))).toBeNull()
    })
  })
})
